# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 505)
        MainWindow.setMinimumSize(QtCore.QSize(505, 505))
        MainWindow.setMaximumSize(QtCore.QSize(505, 505))
        MainWindow.setStyleSheet("")
        self.main_window = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setStyleSheet("background: plum; border-radius: 4px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setStyleSheet(
            "QPushButton{background: transparent; color: white; border: 2px solid white; border-radius: 4px;}\n"
            "QPushButton::hover{background: white; color: black; border: 2px solid black; border-radius: 4px;}\n"
            "QPushButton::pressed{background: darkgrey; color: white; border: 2px solid black; border-radius: 4px;}"
        )
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.verticalLayout_14.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout_14.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.frame_10)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Small")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_14.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Small")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_14.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addWidget(
            self.frame_10, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        self.verticalLayout_12.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_over = QtWidgets.QFrame(self.main_window)
        self.frame_over.setMinimumSize(QtCore.QSize(505, 505))
        self.frame_over.setMaximumSize(QtCore.QSize(505, 505))
        self.frame_over.setStyleSheet(
            "QFrame#frame_over{background: rgba(0, 0, 0, 100);}"
        )
        self.frame_over.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_over.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_over.setObjectName("frame_over")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_over)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_11 = QtWidgets.QFrame(self.frame_over)
        self.frame_11.setMinimumSize(QtCore.QSize(300, 250))
        self.frame_11.setMaximumSize(QtCore.QSize(300, 250))
        self.frame_11.setStyleSheet("QFrame{background: plum; border-radius: 4px;}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setMinimumSize(QtCore.QSize(300, 150))
        self.frame_12.setMaximumSize(QtCore.QSize(300, 150))
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_16.addWidget(
            self.label_3, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_3.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton_3.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Small")
        font.setPointSize(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(
            "QPushButton{background: transparent; color: white; border: 2px solid white; border-radius: 4px;}\n"
            "QPushButton::hover{background: white; color: black; border: 2px solid black; border-radius: 4px;}\n"
            "QPushButton::pressed{background: darkgrey; color: white; border: 2px solid black; border-radius: 4px;}"
        )
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_16.addWidget(
            self.pushButton_3, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        self.horizontalLayout.addWidget(self.frame_12)
        self.verticalLayout_15.addWidget(
            self.frame_11, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        # self.verticalLayout_11.addWidget(self.frame_over)
        self.frame_main = QtWidgets.QFrame(self.page_2)
        self.frame_main.setMinimumSize(QtCore.QSize(495, 495))
        self.frame_main.setMaximumSize(QtCore.QSize(495, 495))
        self.frame_main.setStyleSheet(
            "QFrame{background: white;}\n"
            "QFrame#frame_main{background: black; border: 4px solid white;}\n"
            "QPushButton::hover{background: lightblue; border-radius: 4px;}"
        )
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.gridLayout_main = QtWidgets.QGridLayout(self.frame_main)
        self.gridLayout_main.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_main.setSpacing(1)
        self.gridLayout_main.setObjectName("gridLayout_main")
        self.frame_1 = QtWidgets.QFrame(self.frame_main)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_1)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setSpacing(2)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.verticalLayout_2.addLayout(self.gridLayout_1)
        self.gridLayout_main.addWidget(self.frame_1, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_main)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_two = QtWidgets.QGridLayout()
        self.gridLayout_two.setSpacing(2)
        self.gridLayout_two.setObjectName("gridLayout_two")
        self.verticalLayout_4.addLayout(self.gridLayout_two)
        self.gridLayout_main.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_main)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout_main.addWidget(self.frame_3, 0, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_main)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.gridLayout_main.addWidget(self.frame_5, 1, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_main)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.gridLayout_main.addWidget(self.frame_6, 1, 2, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_main)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_7.addLayout(self.gridLayout_7)
        self.gridLayout_main.addWidget(self.frame_7, 2, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_main)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setContentsMargins(3, 1, 1, 1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_8.addLayout(self.gridLayout_8)
        self.gridLayout_main.addWidget(self.frame_8, 2, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_main)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSpacing(2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_9.addLayout(self.gridLayout_9)
        self.gridLayout_main.addWidget(self.frame_9, 2, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_main)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_10.addLayout(self.gridLayout_4)
        self.gridLayout_main.addWidget(self.frame_4, 1, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_main)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("background: plum;")
        self.page_3.setObjectName("page_3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.scrollArea = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea.setStyleSheet(
            "QScrollArea{background: plum; border-radius: 10px;}\n"
            "\n"
            "QLabel{background: white; color: black; border-radius: 4px; padding: 6px;}"
        )
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 480, 940))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_2 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Small")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_19.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.label_4 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Small")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_19.addWidget(self.label_4, 0, QtCore.Qt.AlignTop)
        self.label_5 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Small")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_19.addWidget(self.label_5, 0, QtCore.Qt.AlignTop)
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Small")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_19.addWidget(self.label_6, 0, QtCore.Qt.AlignTop)
        self.label_7 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Small")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_19.addWidget(self.label_7, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_18.addWidget(
            self.frame_13, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_17.addWidget(self.scrollArea)
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton_4.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Small")
        font.setPointSize(9)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(
            "QPushButton{background: transparent; color: white; border: 2px solid white; border-radius: 4px;}\n"
            "QPushButton::hover{background: white; color: black; border: 2px solid black; border-radius: 4px;}\n"
            "QPushButton::pressed{background: darkgrey; color: white; border: 2px solid black; border-radius: 4px;}"
        )
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_17.addWidget(
            self.pushButton_4, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Super TicTacToe"))
        self.label.setText(_translate("MainWindow", "W E L C O M E"))
        self.pushButton.setText(_translate("MainWindow", "PLAY"))
        self.pushButton_2.setText(_translate("MainWindow", "INSTRUCTIONS"))
        self.label_3.setText(_translate("MainWindow", "X WINS"))
        self.pushButton_3.setText(_translate("MainWindow", "RESTART"))
        self.label_2.setText(
            _translate(
                "MainWindow",
                "The game is played on a 3x3 grid of nine small tic-tac-toe boards.",
            )
        )
        self.label_4.setText(
            _translate(
                "MainWindow", "The first player (X) can play anywhere on any board."
            )
        )
        self.label_5.setText(
            _translate(
                "MainWindow",
                "The next player (O) must play on the board that corresponds \n"
                "to the position of the previous move. \n"
                "For example, if X plays on the top left square of a board, \n"
                "O must play on the top left board.",
            )
        )
        self.label_6.setText(
            _translate(
                "MainWindow",
                "If a board is won by a player or filled completely, \n"
                "no more moves can be played on that board. \n"
                "If a player is sent to such a board, they can play anywhere \n"
                "on any other board.",
            )
        )
        self.label_7.setText(
            _translate(
                "MainWindow",
                "The game ends when a player wins the large board by having \n"
                "three small boards in a row, column, or diagonal, or when \n"
                "there are no legal moves left, in which case the game is a draw.",
            )
        )
        self.pushButton_4.setText(_translate("MainWindow", "PLAY"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
